### ISSUE TITLE
MOV16rmi and related instructions

### ISSUE THREAD

**Issue by krasin** [llvm-dcpu16/llvm-dcpu16#100]
This is a tracking bug for the inline comments from Anton Korobeynikov here: 1dce60768071be0cbc15bcc04b0ae95b145a640b

**Comment by ghost** [comment]
Before I blame myself. How about his:

```
def ZEXT8 : I16rm<0x0,
                    (outs GR16:$dst), (ins GR16:$src),
                    "AND\t{$dst, 0xFF} ; The Notch order",
                    []>;

def : Pat<(zextloadi8 addr:$addr), (i16 (ZEXT8 (MOV16rm addr:$addr)))>;
```

Following C code:

```
int func(int x) {
    if (x&1) {
        return 0;
    }
    return 1;
}
```

Compiles to:

```
        SUB     I, 4 ; The Notch order
        SET     [I], A ; The Notch order
        SET     A, [I] ; The Notch order
        AND     A, 0xFF ; The Notch order
        AND     A, 1 ; The Notch order
        SET     O, 65535 ; The Notch order
        IFE     A, 0 ; The Notch order
        SET     O, 0 ; The Notch order
        IFG     A, 0 ; The Notch order
        SET     O, 1 ; The Notch order
        IFE     O, 0 ; The Notch order
        SET     PC, .LBB0_2 ; The Notch order
```

A little inefficient code, but I only BEGIN to understand how peephole patterns are working.

Edite: I removed the MOV16rmi etc. functions again.

**Comment by krasin** [comment]
Hey, Nils! :)

Don't take it too close to your heart. We're supposed to have fun and learn new things. From what I see, we're succeeding in this.

Regarding to the quality of this code, it's #78. I have almost understood how lowering works and once I've got multiclasses in TableGen, it should be fixed soon.

**Comment by ghost** [comment]
Oh, and I still don't know why we need to zext in this case (Since we do two ANDs directly after each other and the content from 'A' HAS to be i16...).

Okay, enough for today.

**Comment by asl** [comment]
Yes, something like this should work. Just make sure everything is ok with endianness.

**Comment by krasin** [comment]
I am not sure how endianness is related here. This machine has a word addressable memory. It's up to us how to store i8 in i16 register and it seems logical to have i8 as a lower byte.

**Comment by asl** [comment]
Ok then. Though it will be better here to expand as load + and at sdag leve. Then DAG combiner might have more power here.

**Comment by krasin** [comment]
"expand as load + and at sdag leve." -- could you please elaborate? I'm not sure, if I understand.

upd. Ahh!! (SET, AND) at SelectionDAG level.

**Comment by asl** [comment]
Well, mostly. But in target-independent manner, so via LOAD and AND SelectionDAG nodes :)

**Comment by asl** [comment]
Btw, as for "word addressable memory" Make sure stuff like:

```
char foo(char* bar) { return bar[0]; }
char foo(char* bar) { return bar[1]; }
char foo(char* baz, unsigned N) { return baz[N]; }
```

all return proper results

**Comment by ghost** [comment]
Just wanted to say that right now the code

```
int func(int x) {
    if (x&1) {
        return 0;
    }
    return 1;
}
```

Produces _valid_ and _correct_ code. I testes that with an emulators and it has the desired behavior. As fas as I know, zero extend is needed, if we want to extend a i8 to an i16. But DCPU16 doesn't know any i8! We can't even safe an i8 or load it. How can it be than, that we need to zero extend an i8? Could somebody please explain that to me?

**Comment by asl** [comment]
Consider you have:

unsigned char add(unsigned char a, unsigned char b) {
  return a + b;
}

What this code should compile to?

**Comment by ghost** [comment]
It would compile to something like:

SET A, 0x01 ('char' sized)
SET B, 0x02 ('char' sized)

JMP FUNC
ADD A, B

We can't save char based values. Neither do we care: char needs to be defined as int16! As far as I know, we can't really address char based values, since we either need to extend our pointer to 32bit and do some hacks or need to define our smallest type to be int16. Do I have a fundermental flaw in my logic?

**Comment by asl** [comment]
Well, ok. Not chars, but uint8_t, which one should support to produce C99-compliant compiler. I do not see any problems of supporting 8 bit values. You should just make sure everything wraps properly. E.g. in this example since we're doing 2's compliment arithmetic it'd simple 

SET A, <incoming value>
AND A, 0xFF ; make sure it's 8 bit
SET B, <incoming value>
AND B, 0xFF ; make sure it's 8 bit
ADD A, B
AND A, 0xFF ; make sure it's 8 bit again

Yes, surely 8-bit arithmetic won't be efficient here, but we still can support it perfectly.

**Comment by ghost** [comment]
Ahh okay, so we just make sure that nothing in the higher order bits contain some content we don't want to use (let's say, after a shift operation on a int8). Mhh okay, I see the reason now. But I'm not happy with the implementation in this case: In this case, he zero extends a i8, even thought the code cleary says that it's int16 (x)! Would we now zero extend it, we could (and would) overwrite a i16 value with zeroes in the higher order bits.

**Comment by asl** [comment]
Right. In many cases DAG combiner can prove that everything is ok and the top bits are unused and thus eliminate zero extensions.

As for if (x&1) it's the outcome of compiler optimizations which tends to "shrink" all unused bits.

PS: I have not looked into clang bits at all. It might be possible that they are incorrect and thus the bitcode is MSP430-ish, which has i8 ops and everything is ok :)

**Comment by ghost** [comment]
Okay, I tested just now what llvm/vlang does, when we use i16 values (like 0x8000) in this test: He will still use i8 and wants to zero extend it. Quite odd, if you ask me...

**Comment by asl** [comment]
Well, I don't think it's odd. The 16 bit value is used in condition. There it's implicitly converted to "boolean" value zero/not zero. Such value is represented as i1 in LLVM IR (= result of icmp). i1's are not native thus they should properly lowered. We specified that the proper way is to promote stuff to i8. Ok, but it's not possible to promote stuff further because zext'ness will be lost. Thus we end with zext from i8 to i16.

Conditions were always something... "funny" :)
